export const product = [
    {
        name:"name",
        price:"340",
        img:"images/products/p1.jpg",
    },
    {
        name:"name",
        price:"340",
        img:"images/products/p2.jpg",
    },
    {
        name:"name",
        price:"340",
        img:"images/products/p3.jpg",
    },
    {
        name:"name",
        price:"340",
        img:"images/products/p4.jpg",
    },
    {
        name:"name",
        price:"340",
        img:"images/products/p5.jpg",
    },{
        name:"name",
        price:"340",
        img:"images/products/p6.jpg",
    },
    {
        name:"name",
        price:"340",
        img:"images/products/p7.jpg",
    },
    {
        name:"name",
        price:"340",
        img:"images/products/p8.jpg",
    },
    {
        name:"name",
        price:"340",
        img:"images/products/p9.jpg",
    },
]